config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'post#index', as: 'home'
  get "about" => "page#about"
  resources :post, as: 'posts'	# Fix plural _path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true,
		length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def about
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if (@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def create
		@post = Post.new(post_params)
		if (@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <nav>
  		<ul>
  			<li><%= link_to 'Home', home_path %></li>
  			<li><%= link_to 'Create Post', new_post_path %></li>
  		</ul>
	  </nav>

    <%= yield %>
  </body>
</html>

app/views/page/about.html.erb
<h3>About page</h3>

app/views/post/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<div class="alert alert-danger"><%= msg %></div>
			<% end %>
		</ul>
	<% end %>
	<div class="form-group row">
		<!-- <label for="title" class="col-sm-2 col-form-label">Title</label> -->
		<%= f.label :title %>
		<div class="col-sm-10">
			<!-- <input name="title" type="text" class="form-control" id="title"> -->
			<%= f.text_field(:title, {:class => 'form-control'}) %>
		</div>
	</div>
	<div class="form-group row">
		<!-- <label for="inputPassword" class="col-sm-2 col-form-label">Body</label> -->
		<%= f.label :body %>
		<div class="col-sm-10">
			<!-- <textarea name="body" class="form-control" id="body"></textarea> -->
			<%= f.text_area :body %>
		</div>
	</div>
	<!-- <button type="submit" class="btn btn-primary">Submit</button> -->
	<%= f.submit({:class=>'btn btn-primary'}) %>
<% end %>

app/views/post/edit.html.erb
<h3>Edit post: <%= @post.title %></h3>
<%= render 'form' %>

app/views/post/index.html.erb
<h3>Hello from post</h3>
<% @posts.each do |post| %>
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	<%=  link_to 'Show', post_path(post) %>
	<%= link_to 'Edit', edit_post_path(post) %>
	<%= link_to 'Destroy', post_path(post),
		method: :delete,
		data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/post/new.html.erb
<h3>Add new post</h3>
<%= render 'form' %>

app/views/post/show.html.erb
<h3>Show post: <%= @post.title %></h3>

<div>
	<h4>Content:</h4>
	<p><%= @post.body %></p>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', post_path %>